In [34]:
#Gerekli kütüphaneler
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [6]:
!pip install scikit-learn

In [13]:
import sys
!{sys.executable} -m pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 3.1 MB/s eta 0:00:00a 0:00:01


In [25]:
#Algoritmalar
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from xgboost import XGBClassifier

In [15]:
#Veri setini yükleme
iris = load_iris()
X, y = iris.data, iris.target

In [18]:
#Eğitim/test ayrımı
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
#Veriyi ölçeklendirme (özellikle SVM, ... ve ANN için önemli)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [83]:
#Model Değerleme Fonksiyonu
def evuluate_model(model, X_test, y_test, name, class_names):
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"\n=== (name) ===")
    print("Accuracy: ", round(acc, 4))
    print("Classification Report:\n", classification_report(y_test, y_pred, target_name=class_names))

In [95]:
#Yapay Sinir Ağları (ANN)
mlp = MLPClassifier(hidden_layer_sizes=(10,10), max_iter=(1000))
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 100.00%


In [91]:
'''#Destek Vektör Makineleri
svm = SVC()
svm.fit(X_train, y_train)
y_pre=svm.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")'''

'#Destek Vektör Makineleri\nsvm = SVC()\nsvm.fit(X_train, y_train)\ny_pre=svm.predict(X_test)\n\naccuracy = accuracy_score(y_test, y_pred)\nprint(f"Accuracy: {accuracy*100:.2f}%")'

In [92]:
'''#Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")'''

'#Random Forest\nrf = RandomForestClassifier()\nrf.fit(X_train, y_train)\ny_pred = rf.predict(X_test)\n\naccuracy = accuracy_score(y_test, y_pred)\nprint(f"Accuracy: {accuracy*100:.2f}%")'

In [77]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall = recall_score(y_test, y_pred, average="weighted")
f1 = f1_score(y_test, y_pred, average="weighted")
cm = confusion_matrix(y_test, y_pred)

print("ANN Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Scrore: ", f1)
print("\nConfusion Matrix\n", cm)
      
#Daha detaylı bir rapor için
print("\nClassification Report\n", classification_report(y_test, y_pred))

ANN Accuracy:  0.9666666666666667
Precision:  0.9694444444444444
Recall:  0.9666666666666667
F1 Scrore:  0.9664109121909632

Confusion Matrix
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

